### ISSUE TITLE
using a maintained soap library instead of deprecated python-suds

### ISSUE THREAD

**Issue by ChristophBerg** [ClusterLabs/fence-agents#17]
From Debian bug #788079: (http://bugs.debian.org/788079)

```
Date: Mon, 08 Jun 2015 14:03:07 +0200
From: Mathias Behrle <mathiasb@m9s.biz>
Reply-To: Mathias Behrle <mathiasb@m9s.biz>, 788079-maintonly@bugs.debian.org
To: maintonly@bugs.debian.org
Subject: [Debian-ha-maintainers] Bug#788079: fence-agents: Please use a maintained
        soap library instead of deprecated python-suds.

Package: fence-agents
Severity: important
User: maintainers@debian.tryton.org
Usertags: migrate-suds

Dear maintainer of fence-agents,

your package is listed as a Reverse Depend of the python-suds
package, which is now deprecated due to long time missing upstream
maintenance as well as missing compatibility for Python3 (#783029,
#774948, #782970). It is planned to remove python-suds before the
release of stretch.

Please consider to migrate your package to use a maintained soap
library (like pysimplesoap, at the time of writing in NEW).

Thanks for your work!

Best, Mathias
```

**Comment by marxsk** [comment]
Hi,

I will keep this issue open for anyone but I do not plan to work on that in near/mid- future. 

Justification:
It was quite a long time ago when I have chosen suds over other soap implementations. In fence agents there are just two agents that use it. 

* fence_ovh - there should be no trouble at all because there are no hacks. Issue is that I do not have access to OVH instance so I can't test if it is working or not.

* fence_vmware_soap - Exactly opposite. I can have VMWare instances but there is a work-around that is possible (and undocumented) to set '._type' of SOAP object.

FYI I do not intend to use library that is not available in Fedora/CentOS/.. where I develop fence-agents.

**Comment by ChristophBerg** [comment]
python-suds found a new maintainer in Debian, so there is no longer a need to migrate away from it. Closing this issue.
